################################################################################
# ColdBox Docker Compose Stack
# This can be used to quickly run your ColdBox application in a CommandBox based Docker Container.
#
# We pull the latest image, you can change this to a specific tag or CFML engine, which we recommend.
# https://hub.docker.com/repository/docker/ortussolutions/commandbox
#
# Database
# - We give you three databases for you to choose from below: MySQL 8, PostgreSQL, Azure MSSQL
################################################################################
services:

  # ColdBox Site
  wha-coldfusion-api:
    container_name: ${APPNAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # depends_on:
    #   - api_db
    image: ortussolutions/commandbox:lucee5
    # Environment Variables
    environment:
      CFCONFIG_ADMINPASSWORD: ${CFCONFIG_ADMINPASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
      TZ: ${TZ}
    ports:
      - "8080:8080"
      - "8443:8443"
    # Data & Overrides
    volumes:
      - ./:/app
